version: '3'
services:
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=pizzeria
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db
    restart: always
volumes:
  mongodb_data:
